name: Build & Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy NodeJS App
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            mkdir -p ~/deployment
            cd ~/deployment
            git clone https://github.com/butterpigx/upcloud-github-actions.git 
            cd upcloud-github-actions
            # Add any additional deployment steps here
            echo 'Deployment Successful to UpCloud'
