name: Build & Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Debug - Print Secret Availability
        run: |
          echo "SSH_HOST is set: ${{ secrets.SSH_HOST != '' }}"
          echo "SSH_USERNAME is set: ${{ secrets.SSH_USERNAME != '' }}"
          echo "SSH_KEY is set: ${{ secrets.SSH_KEY != '' }}"
          echo "First character of SSH_HOST: ${{ secrets.SSH_HOST != '' && secrets.SSH_HOST[0] || 'Not available' }}"
          echo "Length of SSH_HOST: ${{ secrets.SSH_HOST != '' && secrets.SSH_HOST.length || 'Not available' }}"
      - name: Deploy NodeJS App
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            echo "Connected to host"
            hostname
            pwd
            mkdir -p ~/deployment
            cd ~/deployment
            touch hello-world.txt
            # Add any additional deployment steps here
            echo 'Deployment Successful to UpCloud'
      - name: Debug - Print Environment Variables
        if: always()
        run: |
          echo "Environment variables (sanitized):"
          env | grep -v -e PASSWORD -e KEY | sort
