name: Build & Deploy Hugo Site

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build Hugo site
        run: hugo --minify

      - name: Install Nginx on UpCloud
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            sudo apt update
            sudo apt install -y nginx
            sudo systemctl start nginx
            sudo systemctl enable nginx
            
            # Create a new Nginx server block
            echo "server {
                listen 80;
                server_name $(curl -s ifconfig.me);  # Uses the public IP
                root /var/www/hugo-site;
                index index.html;
                location / {
                    try_files \$uri \$uri/ =404;
                }
            }" | sudo tee /etc/nginx/sites-available/hugo-site
            
            sudo ln -s /etc/nginx/sites-available/hugo-site /etc/nginx/sites-enabled/
            sudo nginx -t && sudo systemctl reload nginx
            
            sudo mkdir -p /var/www/hugo-site
            sudo chown -R $USER:$USER /var/www/hugo-site

      - name: Deploy to UpCloud
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "public/*"
          target: "/var/www/hugo-site"
          strip_components: 1

      - name: Finalize deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            echo "Hugo site deployed successfully"
            echo "You can now access your site at http://$(curl -s ifconfig.me)"
