name: Build & Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Debug - Print Secret Availability
        run: |
          echo "SSH_HOST is set: ${{ env.SSH_HOST != '' }}"
          echo "SSH_USERNAME is set: ${{ env.SSH_USERNAME != '' }}"
          echo "SSH_KEY is set: ${{ env.SSH_KEY != '' }}"
          echo "First character of SSH_HOST: ${{ env.SSH_HOST != '' && env.SSH_HOST[0] || 'Not available' }}"
          echo "Length of SSH_HOST: ${{ env.SSH_HOST != '' && env.SSH_HOST.length || 'Not available' }}"

      - name: Deploy NodeJS App
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USERNAME }}
          key: ${{ env.SSH_KEY }}
          port: 22
          script: |
            echo "Connected to host"
            hostname
            pwd
            mkdir -p ~/deployment
            cd ~/deployment
            git clone https://github.com/butterpigx/upcloud-github-actions.git 
            cd upcloud-github-actions
            # Add any additional deployment steps here
            echo 'Deployment Successful to UpCloud'

      - name: Debug - Print Environment Variables
        if: always()
        run: |
          echo "Environment variables (sanitized):"
          env | grep -v -e PASSWORD -e KEY | sort
